### ISSUE TITLE
Update this manuscript's thumbnail

### ISSUE THREAD

**Issue by vincerubinetti** [greenelab/text_mined_hetnet_manuscript#31]
Hello Manubot user.

If you were not already aware, your paper is being showcased in the [Manubot Catalog](https://manubot.org/catalog/).

Previously, we were making our own thumbnails for each paper, and hosting them in the same repository as `manubot.org`. But now we are moving to a system of having each paper store its thumbnail in its own repository, and linking to it from there.

Here is our suggested thumbnail for your paper that follows the new [thumbnail guidelines](https://github.com/manubot/catalog#thumbnail-guidelines):

![New Project (3)](https://user-images.githubusercontent.com/8326331/64816858-8f630800-d576-11e9-8090-bcb39d190657.png)

Please place this image *in the root of your repository* with the name `thumbnail.png`. Once you have, let us know in this issue and we'll do the rest to update the catalog.

**Comment by vincerubinetti** [comment]
@dhimmel can you take care of this, I'm doing a catalog update today and would like to catch as many as possible

**Comment by dhimmel** [comment]
@danich1 can you add this to the repo?

**Comment by danich1** [comment]
Yeah adding shortly.
