### ISSUE TITLE
Updated Paper Title

### ISSUE THREAD

**Issue by danich1** [greenelab/text_mined_hetnet_manuscript#43]
Given the updated results and conclusions. This paper needs a new title. I'm opening up this issue as a discussion on possible paper titles:

Expanding Hetionet via Multi-Relation Extraction from Biomedical Abstracts
Using Weak Supervision to extract Multiple Relationships from Biomedical Abstracts
 
More titles to come as this paper is being rewritten.

**Comment by cgreene** [comment]
I think that hetionet is probably too specific to include in the title. The term is well-known within our lab, but probably not too far beyond that. You could do:
"Expanding a Database-derived Biomedical Knowledge Graph via Multi-relation Extraction from Biomedical Abstracts"
If you like the theme of the first one.
